In [2]:
import pandas as pd

df =pd.read_csv('../../Data/ProcessedData/LCK_2023_SUMMER_DROP_NAN.csv')

player_counts = df['Player'].value_counts()
players_to_keep = player_counts[player_counts > 25].index
df = df[df['Player'].isin(players_to_keep)]

Top_df = df[df['Role'] == 'TOP']
Win_Top_df = Top_df[Top_df['Result'] == 'Win']
Lose_Top_df = Top_df[Top_df['Result'] == 'Lose']

In [3]:
Top_df['Player'].value_counts()

Morgan    45
Rascal    43
DnDn      43
kingen    41
Zeus      41
Kiin      40
Canna     40
Doran     39
DuDu      38
Name: Player, dtype: int64

In [4]:
non_object_columns = Win_Top_df.select_dtypes(exclude=['object']).columns
Win_Top_df_avg = Win_Top_df.groupby('Player')[non_object_columns].mean()

Win_Top_df_avg['DMG%']

Player
Canna     0.216125
DnDn      0.239615
Doran     0.238344
DuDu      0.277700
Kiin      0.227471
Morgan    0.247600
Rascal    0.208125
Zeus      0.239762
kingen    0.228630
Name: DMG%, dtype: float64

In [5]:
avg_win_stats = (Win_Top_df_avg / Win_Top_df[non_object_columns].mean())
avg_stats = Top_df.groupby('Player')[non_object_columns].mean() / Top_df[non_object_columns].mean()
avg_lose_stats = Lose_Top_df.groupby('Player')[non_object_columns].mean() / Lose_Top_df[non_object_columns].mean()

In [6]:
avg_lose_stats

,Level,Kills,Deaths,Assists,CS,CS in Jungle,CSM,Golds,GPM,GOLD%,...,Total Damage Shielded On Teammates,Time ccing others,Total Time CC Dealt,Total damage taken,Total Time Spent Dead,Consumables purchased,Items Purchased,Shutdown bounty collected,Shutdown bounty lost,Version
Player,,,,,,,,,,,,,,,,,,,,,
Canna,1.009535,1.137222,1.033573,1.138780,0.976129,1.102552,0.954181,1.014289,0.992029,0.984660,...,0.000000,0.803766,0.248207,0.990550,0.989981,1.062035,0.936195,0.783451,0.441079,1.000042
DnDn,0.991034,0.659259,1.072410,0.872091,0.959394,0.336016,0.993830,0.938858,0.974526,0.973135,...,1.325032,1.104919,1.784196,1.006761,1.073666,1.269420,1.188124,0.668545,0.418209,1.000061
Doran,0.928520,0.452063,1.245656,0.934383,0.860968,0.909517,0.927745,0.865202,0.938010,0.947013,...,1.439061,0.932832,1.211138,0.919552,1.148251,0.671438,0.833041,0.214889,0.000000,1.000028
DuDu,1.013557,1.243175,0.923504,1.034496,1.078475,1.108473,1.055245,1.067005,1.040813,1.028532,...,0.655176,1.142897,1.461947,1.097307,0.953484,0.766128,0.886408,1.325151,1.624292,1.000300
Kiin,1.018920,1.582222,0.952140,1.012248,1.025609,1.061103,1.045817,1.032675,1.052056,1.021947,...,0.000000,0.681228,0.306185,0.876248,0.959684,0.763259,1.105515,1.337089,2.483113,0.999629
Morgan,1.040371,1.081185,0.841892,0.716360,1.107023,1.405961,1.071403,1.072331,1.037208,1.036203,...,1.284506,0.930458,1.021748,1.011421,0.832927,1.144888,1.117663,1.637934,1.385316,0.999959
Rascal,0.958143,0.996214,1.113614,0.968990,0.913415,0.884252,0.947214,0.936273,0.968052,1.002577,...,1.408735,0.911997,0.453749,1.048025,1.126000,0.763259,0.855795,1.039958,0.958395,0.999798
Zeus,1.023210,1.028444,1.052365,1.471654,1.034662,1.478912,0.972914,1.063567,1.000698,0.982045,...,0.127003,1.059227,0.631147,0.963636,1.058763,1.156940,1.020475,0.451268,1.411454,0.999985
kingen,0.969889,0.904127,0.902027,1.067867,0.904016,0.776879,0.959076,0.911171,0.971640,0.978226,...,2.194257,1.117974,0.980475,0.829813,0.920847,1.007157,0.931964,0.895372,0.168030,0.999865

In [13]:
Win_Top_df.groupby('Player')['GPM'].describe()

        count        mean        std    min     25%    50%     75%    max
Player
Canna    24.0  411.291667  45.614147  322.0  392.25  413.0  423.00  496.0
DnDn     13.0  403.692308  38.670369  348.0  371.00  404.0  435.00  459.0
Doran    32.0  447.031250  58.372267  300.0  408.00  453.5  476.00  551.0
DuDu     10.0  439.600000  57.656454  352.0  414.00  428.0  462.25  571.0
Kiin     34.0  426.205882  37.773471  360.0  399.25  414.5  461.25  499.0
Morgan   15.0  433.400000  33.712651  365.0  422.00  437.0  451.00  483.0
Rascal   16.0  435.312500  54.563381  360.0  407.75  417.0  454.75  547.0
Zeus     21.0  418.476190  48.314200  335.0  393.00  416.0  443.00  515.0
kingen   27.0  415.074074  48.926103  311.0  388.50  420.0  446.00  536.0

In [14]:
Win_Top_df.groupby('Player')['VSPM'].describe()

        count      mean       std   min    25%    50%    75%   max
Player
Canna    24.0  1.070000  0.230651  0.61  0.930  1.085  1.200  1.48
DnDn     13.0  1.272308  0.231018  1.02  1.140  1.180  1.340  1.85
Doran    32.0  1.000938  0.163773  0.55  0.960  1.015  1.120  1.27
DuDu     10.0  1.096000  0.249942  0.57  0.975  1.160  1.285  1.36
Kiin     34.0  1.045000  0.194706  0.57  0.930  1.065  1.145  1.56
Morgan   15.0  1.168667  0.216097  0.85  1.040  1.110  1.285  1.71
Rascal   16.0  1.148125  0.270757  0.66  0.980  1.080  1.315  1.63
Zeus     21.0  1.010000  0.210855  0.50  0.900  1.000  1.130  1.45
kingen   27.0  1.238889  0.289553  0.78  1.060  1.220  1.415  1.96

In [33]:
Zeus = Top_df[Top_df['Player']== 'Zeus']

In [34]:
Zeus['GPM']

110     430
125       0
130     393
200     466
210     470
295     328
300     329
370     515
380     326
390     350
460     379
470     355
485     423
545     285
550     379
715     373
720     341
800     438
810     406
980     317
995     355
1085    343
1090    387
1120    345
1130    486
1145    475
1220    434
1235    401
1400    334
1410    388
1545    337
1555    397
1635    443
1645    430
1740    363
1755    416
1805    386
1810    390
1825    350
1905    381
1910    408
1920    335
Name: GPM, dtype: int64

In [40]:
df.columns

Index(['Player', 'Champion', 'Role', 'Level', 'Kills', 'Deaths', 'Assists',
       'KDA', 'CS', 'CS in Jungle', 'CSM', 'Golds', 'GPM', 'GOLD%',
       'Vision Score', 'Wards placed', 'Wards destroyed',
       'Control Wards Purchased', 'Detector Wards Placed', 'VSPM', 'WPM',
       'VWPM', 'WCPM', 'VS%', 'Total damage to Champion', 'Physical Damage',
       'Magic Damage', 'True Damage', 'DPM', 'DMG%', 'K+A Per Minute', 'KP%',
       'Solo kills', 'Double kills', 'Triple kills', 'Quadra kills',
       'Penta kills', 'GD@15', 'CSD@15', 'XPD@15', 'LVLD@15',
       'Objectives Stolen', 'Damage dealt to turrets',
       'Damage dealt to buildings', 'Total heal', 'Total Heals On Teammates',
       'Damage self mitigated', 'Total Damage Shielded On Teammates',
       'Time ccing others', 'Total Time CC Dealt', 'Total damage taken',
       'Total Time Spent Dead', 'Consumables purchased', 'Items Purchased',
       'Shutdown bounty collected', 'Shutdown bounty lost', 'Version', 'Date',
       'Team', 'Result'],
      dtype='object')

In [43]:
AD_df = df[df['Role'] == 'ADC']

AD_df['Player'].value_counts()

Hena        45
Paduck      43
Viper       41
Gumayusi    41
Aiming      40
Teddy       39
Peyz        39
Taeyoon     38
Deft        37
Jiwoo       36
Name: Player, dtype: int64