In [2]:
import pandas as pd

df = pd.read_csv('../../../RawData/GameStats/LCK_2023_SUMMER.csv')
df

,Player,Champion,Role,Level,Kills,Deaths,Assists,KDA,CS,CS in Team's Jungle,...,Damage self mitigated,Total Damage Shielded On Teammates,Time ccing others,Total Time CC Dealt,Total damage taken,Total Time Spent Dead,Consumables purchased,Items Purchased,Shutdown bounty collected,Shutdown bounty lost
0,Kiin,Gangplank,TOP,16,2,1,8,10,252,4.0,...,8267.0,0,5.0,156,13570.0,42,7,22,0,100
1,Cuzz,Viego,JUNGLE,15,8,2,10,9,182,156.0,...,24001.0,0,12.0,198,23779.0,66,5,24,0,150
2,Bdd,Ahri,MID,15,7,3,10,5.7,219,0.0,...,10336.0,0,22.0,77,16177.0,114,7,23,100,500
3,Aiming,Tristana,ADC,15,0,2,13,6.5,264,12.0,...,6309.0,0,4.0,53,9404.0,33,6,23,0,0
4,Lehends,Alistar,SUPPORT,12,2,3,11,4.3,30,0.0,...,16728.0,77,20.0,55,11572.0,49,16,27,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2065,kingen,K'Sante,TOP,15,1,1,1,2,250,3.0,...,16943.0,177,26.0,1669,13981.0,49,9,28,0,0
2066,Clid,Viego,JUNGLE,13,1,2,1,1,164,154.0,...,16060.0,0,4.0,194,22960.0,36,11,25,0,0
2067,Zeka,Gragas,MID,14,0,3,1,0.3,226,4.0,...,15857.0,0,14.0,474,19369.0,79,8,27,0,0
2068,Viper,Jinx,ADC,13,0,1,1,1,265,16.0,...,6312.0,0,11.0,92,10485.0,43,5,23,0,50
2069,Life,Milio,SUPPORT,9,0,3,1,0.3,12,0.0,...,3916.0,3014,8.0,53,7027.0,73,13,26,0,0

In [4]:
df['Player'].value_counts()

UmTi       45
Hena       45
Morgan     45
Effort     45
Rascal     43
           ..
Hype        1
PerfecT     1
HamBak      1
Feisty      1
Way         1
Name: Player, Length: 75, dtype: int64

In [10]:
less_than_10 = df['Player'].value_counts() <= 10

less_than_10.index[less_than_10 == True]

Index(['Ivory', 'Kyeahoo', 'Vital', 'Rahel', 'Sponge', 'SeTab', 'deokdam',
       'Pleata', 'Mihile', 'Sounda', 'Callme', 'Frog', 'HH', 'Hype', 'PerfecT',
       'HamBak', 'Feisty', 'Way'],
      dtype='object')

In [24]:
df['Player'].isin(less_than_10.index[less_than_10 == False])

0       True
1       True
2       True
3       True
4       True
        ...
2065    True
2066    True
2067    True
2068    True
2069    True
Name: Player, Length: 2070, dtype: bool

In [16]:
drop_less_than_10_df = df[df['Player'].isin(less_than_10.index[less_than_10 == False])]

drop_less_than_10_df

,Player,Champion,Role,Level,Kills,Deaths,Assists,KDA,CS,CS in Team's Jungle,...,Damage self mitigated,Total Damage Shielded On Teammates,Time ccing others,Total Time CC Dealt,Total damage taken,Total Time Spent Dead,Consumables purchased,Items Purchased,Shutdown bounty collected,Shutdown bounty lost
0,Kiin,Gangplank,TOP,16,2,1,8,10,252,4.0,...,8267.0,0,5.0,156,13570.0,42,7,22,0,100
1,Cuzz,Viego,JUNGLE,15,8,2,10,9,182,156.0,...,24001.0,0,12.0,198,23779.0,66,5,24,0,150
2,Bdd,Ahri,MID,15,7,3,10,5.7,219,0.0,...,10336.0,0,22.0,77,16177.0,114,7,23,100,500
3,Aiming,Tristana,ADC,15,0,2,13,6.5,264,12.0,...,6309.0,0,4.0,53,9404.0,33,6,23,0,0
4,Lehends,Alistar,SUPPORT,12,2,3,11,4.3,30,0.0,...,16728.0,77,20.0,55,11572.0,49,16,27,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2065,kingen,K'Sante,TOP,15,1,1,1,2,250,3.0,...,16943.0,177,26.0,1669,13981.0,49,9,28,0,0
2066,Clid,Viego,JUNGLE,13,1,2,1,1,164,154.0,...,16060.0,0,4.0,194,22960.0,36,11,25,0,0
2067,Zeka,Gragas,MID,14,0,3,1,0.3,226,4.0,...,15857.0,0,14.0,474,19369.0,79,8,27,0,0
2068,Viper,Jinx,ADC,13,0,1,1,1,265,16.0,...,6312.0,0,11.0,92,10485.0,43,5,23,0,50
2069,Life,Milio,SUPPORT,9,0,3,1,0.3,12,0.0,...,3916.0,3014,8.0,53,7027.0,73,13,26,0,0

In [34]:
top_df = drop_less_than_10_df[drop_less_than_10_df['Role'] == 'SUPPORT']
print(top_df['Player'].unique())
print(len(top_df['Player'].unique()))

['Lehends' 'Kael' 'BeryL' 'Andil' 'Effort' 'Delight' 'Bible' 'Life'
 'Peter' 'Keria' 'Kellin' 'Jun']
12

In [35]:
team = {
    'KT' : ['Kiin', 'Cuzz', 'Bdd', 'Aiming', 'Lehends'],
    'GEN' : ['Doran', 'Peanut', 'Chovy', 'Peyz', 'Delight'],
    'HLE' : ['kingen', 'Grizzly', 'Clid', 'Zeka', 'Viper', 'Life'],
    'Dplus KIA' : ['Canna', 'Canyon', 'ShowMaker', 'Deft', 'Bible', 'Kellin'],
    'T1' : ['Zeus', 'Oner', 'Faker', 'Poby', 'Gumayusi', 'Keria'],
    'DRX' : ['Rascal', 'Croco','Juhan', 'FATE', 'Paduck', 'BeryL'],
    'LSB' : ['Burdol', 'Clear', 'Willer', 'Clozer', 'Teddy', 'Kael'],
    'BRION' : ['Morgan', 'UmTi', 'Karis', 'Hena', 'Effort'],
    'NS' : ['DnDn','Sylvie', 'FIESTA', 'Quad', 'Jiwoo', 'Peter'],
    'KDF' : ['DuDu', 'YoungJae', 'Bulldog', 'Taeyoon', 'Andil', 'Jun']
}