In [1]:
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/wan6570/FlyAI_Project/Doyoon/API/LeagueofLegends/SILVER.csv')

df

,Player,championName,teamPosition,champLevel,kills,deaths,assists,KDA 0.5,totalMinionsKilled,totalAllyJungleMinionsKilled,...,totalHealsOnTeammates,damageSelfMitigated,totalDamageShieldedOnTeammates,timeCCingOthers,totalTimeCCDealt,trueDamageTaken,totalTimeSpentDead,consumablesPurchased,itemsPurchased,win
0,성실한덕후,KSante,TOP,13,2,4,0,0.444444,152,0,...,0,14453,0,25,1836,137,92,3,18,True
1,곧 갈게,Shaco,JUNGLE,12,6,2,3,3.600000,5,78,...,0,5234,0,17,468,151,51,2,11,True
2,TaeHo9414,Vex,MIDDLE,13,7,1,3,6.666667,159,0,...,0,6600,0,28,380,132,0,6,21,True
3,늑대와 첫날밤,Jhin,BOTTOM,11,7,1,1,5.333333,149,0,...,437,4614,0,29,119,0,0,1,15,True
4,에 쿙,Lux,UTILITY,10,0,4,9,2.000000,7,0,...,0,3325,440,40,151,26,80,2,13,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9075,광고없는유튜브,Kennen,TOP,11,2,2,2,1.600000,124,0,...,0,2617,0,13,19,140,49,3,10,True
9076,앗겸님,Nunu,JUNGLE,9,4,2,4,3.200000,5,61,...,0,7373,0,10,173,10,12,2,11,True
9077,취소입력,Tristana,MIDDLE,11,4,2,3,2.800000,121,0,...,0,3940,0,1,18,69,42,2,14,True
9078,인찡이,Ezreal,BOTTOM,9,9,3,3,3.428571,113,0,...,175,3138,0,0,0,470,34,2,13,True
9079,수땅이,Soraka,UTILITY,8,2,2,12,5.600000,13,0,...,2524,3083,347,15,127,175,48,9,24,True

In [3]:
df['teamPosition'].value_counts()

TOP        1816
JUNGLE     1816
MIDDLE     1816
BOTTOM     1816
UTILITY    1816
Name: teamPosition, dtype: int64